# ... (backend y media_folder igual)
collections:
  - name: "orquideas"
    label: "Mis Orquídeas"
    folder: "_orquideas" # Cambiado a _orquideas
    create: true
    fields:
      - {label: "Nombre", name: "nombre", widget: "string"}
      - {label: "Precio", name: "precio", widget: "string"}
      - {label: "Imagen", name: "imagen", widget: "image"}