backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "tienda"
    label: "Mi Tienda"
    folder: "content/tienda"
    create: true
    delete: true
    fields:
      - {label: "Nombre del Artículo", name: "nombre", widget: "string"}
      - {label: "Precio", name: "precio", widget: "string"}
      - {label: "Descripción", name: "descripcion", widget: "text"}
      - {label: "Imagen", name: "imagen", widget: "image"}

  - name: "granja"
    label: "Mi Granja"
    folder: "content/granja"
    create: true
    delete: true
    fields:
      - {label: "Título", name: "titulo", widget: "string"}
      - {label: "Descripción", name: "descripcion", widget: "text"}
      - {label: "Imagen", name: "imagen", widget: "image"}

  - name: "orquideas"
    label: "Mis Orquídeas"
    folder: "content/orquideas"
    create: true
    delete: true
    fields:
      - {label: "Nombre de la Orquídea", name: "nombre", widget: "string"}
      - {label: "Cuidados", name: "cuidados", widget: "text"}
      - {label: "Imagen", name: "imagen", widget: "image"}
